### ISSUE TITLE
Bot @tagging me

### ISSUE THREAD

**Issue by TechStack** [The-Code-Monkey/PaperCMS#50]
Hi , Would it be possible for you to tweak your bot to not @ mention me on every commit about your techstack ?
Github sends me mails for each of those commits as it is seen as a mention on github.

Thank you

**Comment by The-Code-Monkey** [comment]
If it's the renovate bot, sorry unfortunately not as it not a bot I own. And techstack is the name of my mono repo and npm org. I'm not sure what I can do to fix this.

**Comment by The-Code-Monkey** [comment]
But I will see what I can do.

**Comment by The-Code-Monkey** [comment]
I have put an issue in with the owners of renovate bot hopefully they will address this. But I cannot guarantee anything

**Comment by TechStack** [comment]
Thank you

**Comment by The-Code-Monkey** [comment]
No worries you should have been linked to the issue ticket. I hope you don't mind

**Comment by The-Code-Monkey** [comment]
I have applied the suggested fix let me know if you get any more from this point forwards

**Comment by TechStack** [comment]
My inbox thanks you :)

**Comment by The-Code-Monkey** [comment]
There is a new pr let me know if you got pinged

**Comment by TechStack** [comment]
I did not. Thank you again
